### ISSUE TITLE
Add support for adding data links for the tree panel items

### ISSUE THREAD

**Issue by smipi1** [BrightGrafana/bright-tree-panel#22]
The native Grafana panels allow [Data links to be configured](https://grafana.com/docs/grafana/latest/panels-visualizations/configure-data-links/). Adding a data link allows the user to drill through on data points, numbers and labels by clicking on them. Having support for this in the tree panel makes for a very natural and useful extension.

The mechanism for the native Grafana panels are quite elaborate and flexible, but it would be adequate to add an optional `Node data link field name` under the `Interactive tree panel` options. If this field name is set, the node element text gets surrounded with an `<href>` that points to what is specified.

**Comment by BrightGrafana** [comment]
Thank you for bringing up the idea of adding support for data links in the tree panel. This would be a useful and natural extension to the existing functionality. The suggestion of adding an optional Node data link field name under the Interactive tree panel options seems like a practical solution. This would allow users to navigate away from the dashboard based on the link.

The best way this would work is if the tree has a option to not contract when clicking on labels. #11 and #12

**Comment by BrightGrafana** [comment]
@smipi1 Would the configuration below work?
![image](https://github.com/BrightGrafana/bright-tree-panel/assets/145783411/3bf3c2db-d8ed-4270-baef-183e7b378cf3)

**Comment by smipi1** [comment]
Yes! That would be perfect!

**Comment by BrightGrafana** [comment]
released in 1.4.0

**Comment by smipi1** [comment]
Hi @BrightGrafana ,

I updated to 1.4.0. The Panel options turned out a little different, but it does exactly what I needed it to do! Highly appreciated improvement!

For casual readers, there isn't any proper documentation on how to configure this yet, so I will document it here:

1. Edit the panel options.
2. Under `Interactive Tree Panel`, set the `Click mode` to `Data link`.
3. Under `Data Link`, set the `Data link URL`. You would usually leverage a data field from query here.
4. Optionally select `Open in new tab`.

![Tree-panel-data-link-options](https://github.com/BrightGrafana/bright-tree-panel/assets/5098978/d5f83073-542e-43e5-b62d-bad02483a520)
