### ISSUE TITLE
Disable functionality does not work as one would expect

### ISSUE THREAD

**Issue by ShikaruAriki** [BrightGrafana/bright-tree-panel#28]
# :beetle: Bug Report

### Affected Feature

disabled

### Description

In the first example you can see that by disabling the first element of the tree, all its children are disabled.

![test1](https://github.com/BrightGrafana/bright-tree-panel/assets/14907778/5df1cdb8-e2a7-4265-812f-2fc3be115b4e)

In the second example it can be seen that disabling only the second tree element happens that:

- the first element is enabled as expected
- the second element is disabled as expected
- children of the second element are not enabled as expected

![test2](https://github.com/BrightGrafana/bright-tree-panel/assets/14907778/2c5efcba-d069-4053-8565-79e66349ee80)

Perhaps the disabled feature was designed just as it is working right now, so it is actually not a bug but an architectural choice.

**However what I would have expected is to be able to choose element by element enabled/disabled without having the influence from the parent element.**

I thank you in advance for reading my problem and thank you for what you are doing for the plugin.

_(I don't think it's my best English but I hope you can understand it, in case ask me for clarification and I will try to explain myself better)._

### Current Version

```plaintext
v1.4.2
```

**Comment by BrightGrafana** [comment]
Thank you for reporting this issue and providing detailed examples. It appears that the disabled feature of the "[MUI X Tree View](https://mui.com/x/react-tree-view/)" component is currently working as intended, with the parent element influencing the state of its children. However, you have raised a valid point about the potential for more flexibility in choosing the enabled/disabled state of individual elements without being influenced by the parent element. 

We appreciate your feedback and will investigate if it's possible to add more flexibility.

**Comment by BrightGrafana** [comment]
@ShikaruAriki, we have explored the possibility of adding more flexibility to the disable functionality. However, at the moment, the 'MUI X Tree View' component does not provide this option. We are open to revisiting this if the situation changes in the future.
