### ISSUE TITLE
The tree display does not update when a variable is changed

### ISSUE THREAD

**Issue by Smelentyev** [BrightGrafana/bright-tree-panel#29]
Description
The tree display does not update when a variable is changed

The first one changes the value of the variable and 2 changes its values ​​based on this variable.
The tree is updated in 2 cases: if you enter edit mode or when refreshing the page

We will be grateful if you correct this behavior.

Current Version
v1.4.2

**Comment by BrightGrafana** [comment]
Thank you for submitting the bug report. In order to better understand and reproduce the issue, we would appreciate it if you could provide more detailed information about the bug. Specifically, it would be helpful to know the steps to reproduce the issue, the expected behavior, and any additional information that could help us investigate the problem. 

Thank you for your help in improving this plugin.

**Comment by Smelentyev** [comment]
Test data (postgresql datasource):

```

CREATE TABLE public.time_period (
	
	"time" timestamp NOT NULL,
	"count_block" String NOT NULL,
	"parent" int4 NULL
);


INSERT INTO public.apdex ("time", "count_block", "data") 
VALUES
('2024-03-18 07:01:17', '2024-03-18 07:01:17 (4)', NULL),
('2024-03-18 06:49:47', '2024-03-18 06:49:47 (2)', NULL);


CREATE TABLE public.blocks (
	
	time timestamp NOT NULL,
	"id" integer NOT NULL,
	"parrent_id" int 4 NULL,
	"session_id" String NOT NULL,
	"block_id" String NULL
);

INSERT INTO public.blocks ("id", "parrent_id", "session_id", block_id) 
VALUES
('2024-03-18 06:49:47', 11044909, 11044916, '258', '528'),
('2024-03-18 06:49:47', 11044915, 11044916, '306', '528'),
('2024-03-18 06:49:47', 11044916, NULL, '528', NULL),
('2024-03-18 07:01:17', 11045942, 11045917, '511', '399'),
('2024-03-18 07:01:17', 11045931, 11045917, '422', '399'),
('2024-03-18 07:01:17', 11045922, 11045917, '450', '399'),
('2024-03-18 07:01:17', 11045938, 11045941, '520', '336'),
('2024-03-18 07:01:17', 11045941, NULL, '336', NULL),
('2024-03-18 07:01:17', 11045917, NULL, '399', NULL);
 
```
add to dashboard 2 intercative tree panel and dashboar veriable "select_time"

1.
Query 
`Select * from time_period Where $__timeFilter(time) `
Serrings : 
![image](https://github.com/BrightGrafana/bright-tree-panel/assets/162976428/18cb4a6e-97cd-4749-a022-6c162f59ad52)

2.
Query
Select * from blocks 
Where time between to_timestamp($select_time/1000)-interval '1' second and to_timestamp($select_time/1000)+interval '1' second
Settings :
![image](https://github.com/BrightGrafana/bright-tree-panel/assets/162976428/ae74046a-6274-43d8-a3d5-e37d0e08fca5)

Case 1 :
When the time changes, 1 panel is not updated.
Case 2:
When you select a value in 1 panel, the data in 2 panels is not updated

**Comment by i-mediasolutions** [comment]
We tried to reproduce the issue based on the data you provided, but we were unable to reproduce it. Attached you find the database script we used to create the dataset and an export of the dashboard we used to reproduce the issue. Can you please check if you still experience the issue  with the attached dashboard JSON?

[sample_dashboard.json](https://github.com/BrightGrafana/bright-tree-panel/files/14873201/sample_dashboard.json)

```
CREATE TABLE public.time_period (
	"time" timestamp NOT NULL,
	"count_block" text NOT NULL,
	"parent" int4 NULL
);

INSERT INTO public.time_period ("time", "count_block", "parent") 
VALUES ('2024-03-18 07:01:17', '2024-03-18 07:01:17 (4)', NULL),
('2024-03-18 06:49:47', '2024-03-18 06:49:47 (2)', NULL);

CREATE TABLE public.blocks (
	time timestamp NOT NULL,
	"id" integer NOT NULL,
	"parrent_id" int4 NULL,
	"session_id" text NOT NULL,
	"block_id" text NULL
);

INSERT INTO public.blocks ("time", "id", "parrent_id", "session_id", block_id) 
VALUES ('2024-03-18 06:49:47', 11044909, 11044916, '258', '528'),
('2024-03-18 06:49:47', 11044915, 11044916, '306', '528'),
('2024-03-18 06:49:47', 11044916, NULL, '528', NULL),
('2024-03-18 07:01:17', 11045942, 11045917, '511', '399'),
('2024-03-18 07:01:17', 11045931, 11045917, '422', '399'),
('2024-03-18 07:01:17', 11045922, 11045917, '450', '399'),
('2024-03-18 07:01:17', 11045938, 11045941, '520', '336'),
('2024-03-18 07:01:17', 11045941, NULL, '336', NULL),
('2024-03-18 07:01:17', 11045917, NULL, '399', NULL);
```
